version: '3'

tasks:
  upload-lambdas:
    desc: Build and upload current code as lambdas to buckets defined in WEKACTL_LAMBDAS_BUCKETS env var
    cmds:
      - ./scripts/upload_lambdas.sh
  weka-upload-lambdas:
    desc: Build and upload current code as lambdas to official buckets
    env:
      WEKACTL_AWS_LAMBDAS_BUCKETS: "eu-west-1=weka-wekactl-images-eu-west-1,ap-northeast-2=weka-wekactl-images-ap-northeast-2,ap-northeast-1=weka-wekactl-images-ap-northeast-1,eu-west-2=weka-wekactl-images-eu-west-2,eu-central-1=weka-wekactl-images-eu-central-1,ap-southeast-1=weka-wekactl-images-ap-southeast-1,us-east-1=weka-wekactl-images-us-east-1,us-west-2=weka-wekactl-images-us-west-2,us-east-2=weka-wekactl-images-us-east-2,ap-southeast-2=weka-wekactl-images-ap-southeast-2,sa-east-1=weka-wekactl-images-sa-east-1,ap-south-1=weka-wekactl-images-ap-south-1,us-west-1=weka-wekactl-images-us-west-1"
      AWS_PROFILE: devops
    cmds:
      - ./scripts/upload_lambdas.sh
  weka-upload-lambdas-dev:
    desc: Build and upload current code as lambdas to single official bucket in dev mode
    env:
      WEKACTL_AWS_LAMBDAS_BUCKETS: "eu-central-1=weka-wekactl-images-eu-central-1"
      AWS_PROFILE: devops
      WEKACTL_FORCE_DEV: 1
    cmds:
      - ./scripts/upload_lambdas.sh
  deploy-test:
    desc: Build and upload lambdas and wekactl to single official bucket in dev mode
    env:
      WEKACTL_AWS_LAMBDAS_BUCKETS: "eu-central-1=weka-wekactl-images-eu-central-1"
      WEKACTL_FORCE_DEV: 1
      DEPLOY: 1
    cmds:
      - ./deploy.sh
  deploy-dev:
    desc: Build and upload lambdas and wekactl to official buckets defined in WEKACTL_LAMBDAS_BUCKETS env var
    env:
      WEKACTL_AWS_LAMBDAS_BUCKETS: "eu-west-1=weka-wekactl-images-eu-west-1,ap-northeast-2=weka-wekactl-images-ap-northeast-2,ap-northeast-1=weka-wekactl-images-ap-northeast-1,eu-west-2=weka-wekactl-images-eu-west-2,eu-central-1=weka-wekactl-images-eu-central-1,ap-southeast-1=weka-wekactl-images-ap-southeast-1,us-east-1=weka-wekactl-images-us-east-1,us-west-2=weka-wekactl-images-us-west-2,us-east-2=weka-wekactl-images-us-east-2,ap-southeast-2=weka-wekactl-images-ap-southeast-2,sa-east-1=weka-wekactl-images-sa-east-1,ap-south-1=weka-wekactl-images-ap-south-1,us-west-1=weka-wekactl-images-us-west-1"
      WEKACTL_FORCE_DEV : 1
      DEPLOY: 1
    cmds:
      - ./deploy.sh
  deploy-release:
    desc: Build and upload lambdas and wekactl to official buckets defined in WEKACTL_LAMBDAS_BUCKETS env var
    env:
      WEKACTL_AWS_LAMBDAS_BUCKETS: "eu-west-1=weka-wekactl-images-eu-west-1,ap-northeast-2=weka-wekactl-images-ap-northeast-2,ap-northeast-1=weka-wekactl-images-ap-northeast-1,eu-west-2=weka-wekactl-images-eu-west-2,eu-central-1=weka-wekactl-images-eu-central-1,ap-southeast-1=weka-wekactl-images-ap-southeast-1,us-east-1=weka-wekactl-images-us-east-1,us-west-2=weka-wekactl-images-us-west-2,us-east-2=weka-wekactl-images-us-east-2,ap-southeast-2=weka-wekactl-images-ap-southeast-2,sa-east-1=weka-wekactl-images-sa-east-1,ap-south-1=weka-wekactl-images-ap-south-1,us-west-1=weka-wekactl-images-us-west-1"
      DEPLOY: 1
    cmds:
      - ./deploy.sh
  deploy-ga:
    desc: Build and upload lambdas and wekactl to official buckets defined in WEKACTL_LAMBDAS_BUCKETS env var
    env:
      WEKACTL_AWS_LAMBDAS_BUCKETS: "eu-west-1=weka-wekactl-images-eu-west-1,ap-northeast-2=weka-wekactl-images-ap-northeast-2,ap-northeast-1=weka-wekactl-images-ap-northeast-1,eu-west-2=weka-wekactl-images-eu-west-2,eu-central-1=weka-wekactl-images-eu-central-1,ap-southeast-1=weka-wekactl-images-ap-southeast-1,us-east-1=weka-wekactl-images-us-east-1,us-west-2=weka-wekactl-images-us-west-2,us-east-2=weka-wekactl-images-us-east-2,ap-southeast-2=weka-wekactl-images-ap-southeast-2,sa-east-1=weka-wekactl-images-sa-east-1,ap-south-1=weka-wekactl-images-ap-south-1,us-west-1=weka-wekactl-images-us-west-1"
      DEPLOY: 1
      GA: 1
    cmds:
      - ./deploy.sh

